### ISSUE TITLE
[BUG][DISTRIBUTION][2.0.0] PA failed localmaven in snapshot/non-snapshot pipeline for 2.0.0 GA

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/performance-analyzer#209]
```
> Task :check
> Task :build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 36s
18 actionable tasks: 18 executed

> Configure project :
pa in dir: (../performance-analyzer) will be built.
opensearch_version: (2.0.0), plugin_version: (2.0.0.0-rc1), snapshot: (false), qualifier: (rc1).
PA repo located at '../performance-analyzer' will be used.

> Task :extractIncludeProto UP-TO-DATE
> Task :extractProto UP-TO-DATE
> Task :generateProto UP-TO-DATE
> Task :spotlessJava UP-TO-DATE
> Task :spotlessJavaApply UP-TO-DATE
> Task :spotlessApply UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :generateMetadataFileForMavenPublication
> Task :generatePomFileForMavenPublication
> Task :publishMavenPublicationToMavenLocal
> Task :publishToMavenLocal

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
11 actionable tasks: 3 executed, 8 up-to-date

> Task :updateShas FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':updateShas'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find org.opensearch:performanceanalyzer-rca:2.0.0.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/opensearch/performanceanalyzer-rca/2.0.0.0/performanceanalyzer-rca-2.0.0.0.pom
       - file:/usr/share/opensearch/.m2/repository/org/opensearch/performanceanalyzer-rca/2.0.0.0/performanceanalyzer-rca-2.0.0.0.pom
       - https://plugins.gradle.org/m2/org/opensearch/performanceanalyzer-rca/2.0.0.0/performanceanalyzer-rca-2.0.0.0.pom
       - https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/performanceanalyzer-rca/2.0.0.0/performanceanalyzer-rca-2.0.0.0.pom
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 58s
3 actionable tasks: 3 executed
2022-05-04 18:30:06 ERROR    Error building performance-analyzer, retry with: ./build.sh manifests/2.0.0/opensearch-2.0.0.yml --component performance-analyzer
Traceback (most recent call last):
  File "./src/run_build.py", line 80, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 68, in main
    builder.build(build_recorder)
  File "/var/jenkins/workspace/distribution-build-opensearch@2/src/build_workflow/builder_from_source.py", line 55, in build
    self.git_repo.execute(build_command)
  File "/var/jenkins/workspace/distribution-build-opensearch@2/src/git/git_repository.py", line 83, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash /tmp/tmpw5xb6z0w/performance-analyzer/scripts/build.sh -v 2.0.0 -p linux -a x64 -s false -o builds' returned non-zero exit status 1.
```

**Comment by peterzhuamazon** [comment]
Close this as rc1 is already removed.
