### ISSUE TITLE
[BUG] Fix failing FaultDetectionMetricsCollectorTests test

### ISSUE THREAD

**Issue by sruti1312** [opensearch-project/performance-analyzer#220]
**What is the bug?**
```FaultDetectionMetricsCollectorTests.testFaultDetectionMetrics``` is failing and not reproduce-able locally. It is failing since this commit - https://github.com/opensearch-project/performance-analyzer/pull/214

```
org.opensearch.performanceanalyzer.collectors.FaultDetectionMetricsCollectorTests > testFaultDetectionMetrics FAILED

Suite: Test class org.opensearch.performanceanalyzer.collectors.FaultDetectionMetricsCollectorTests
  2> java.lang.AssertionError: expected:<1> but was:<7>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.performanceanalyzer.collectors.FaultDetectionMetricsCollectorTests.testFaultDetectionMetrics(FaultDetectionMetricsCollectorTests.java:44)
    java.lang.AssertionError: expected:<1> but was:<7>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.performanceanalyzer.collectors.FaultDetectionMetricsCollectorTests.testFaultDetectionMetrics(FaultDetectionMetricsCollectorTests.java:44)
```
https://github.com/opensearch-project/performance-analyzer-rca/runs/6457175983?check_suite_focus=true

**Comment by Tjofil** [comment]
The issue seems not to be happening for as far as the GitHub logs allow us to go back. Marking as closed.
