### ISSUE TITLE
[BUG] PerformanceAnalyzer does not support PKCS#1 encoded private keys

### ISSUE THREAD

**Issue by dancristiancecoi** [opensearch-project/performance-analyzer#605]
**What is the bug?**

PerformanceAnalyzer does not appear to support PKCS#1 encoded private keys when I enable TLS.  

When I use a PKCS#1 private key, I get the following error: 

```
6:23:48.626 [main] ERROR org.opensearch.performanceanalyzer.PerformanceAnalyzerWebServer - Unable to create HttpServer
java.lang.ClassCastException: class org.bouncycastle.openssl.PEMKeyPair cannot be cast to class org.bouncycastle.asn1.pkcs.PrivateKeyInfo (org.bouncycastle.openssl.PEMKeyPair and org.bouncycastle.asn1.pkcs.PrivateKeyInfo are in unnamed module of loader 'app')
        at org.opensearch.performanceanalyzer.CertificateUtils.getPrivateKey(CertificateUtils.java:58) ~[performance-analyzer-rca-2.11.0.0.jar:?]
        at org.opensearch.performanceanalyzer.CertificateUtils.createKeyStore(CertificateUtils.java:68) ~[performance-analyzer-rca-2.11.0.0.jar:?]
        at org.opensearch.performanceanalyzer.PerformanceAnalyzerWebServer.createHttpsServer(PerformanceAnalyzerWebServer.java:108) ~[performance-analyzer-rca-2.11.0.0.jar:?]
        at org.opensearch.performanceanalyzer.PerformanceAnalyzerWebServer.createInternalServer(PerformanceAnalyzerWebServer.java:44) [performance-analyzer-rca-2.11.0.0.jar:?]
        at org.opensearch.performanceanalyzer.PerformanceAnalyzerApp.createClientServers(PerformanceAnalyzerApp.java:348) [performance-analyzer-rca-2.11.0.0.jar:?]
        at org.opensearch.performanceanalyzer.PerformanceAnalyzerApp.createClientServers(PerformanceAnalyzerApp.java:320) [performance-analyzer-rca-2.11.0.0.jar:?]
        at org.opensearch.performanceanalyzer.PerformanceAnalyzerApp.main(PerformanceAnalyzerApp.java:113) [performance-analyzer-rca-2.11.0.0.jar:?]
```
Here is the relevant section of the config: 

```
https-enabled = true
certificate-file-path = /usr/share/elasticsearch/config/tls/nodecert.pem
private-key-file-path = /usr/share/elasticsearch/config/tls/nodekey.pem   
```

The key has this format: 

```
-----BEGIN RSA PRIVATE KEY-----
base64-encoded Bytes
-----END RSA PRIVATE KEY-----
```

PKCS#8 encoded private keys work fine. Furthermore,  everything works correctly if I convert the previously failing  private key to PKCS#8

**What is the expected behavior?**
PerformanceAnalyzer should start correctly when using a PKCS#1/RSA private key 

**What is your host/environment?**
OpenSearch 2.11 running in a Red Hat Enterprise Linux 8 container

**Comment by dblock** [comment]
[Triage -- attendees [1](https://github.com/dblock), [2](https://github.com/peternied), [3](https://github.com/reta), [4](https://github.com/krisfreedain), [5](https://github.com/Getsaurabh02), [6](https://github.com/gkamat), [7](https://github.com/scrawfor99)]

Looks like a valid feature request.
