### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by dblock** [opensearch-project/performance-analyzer#75]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/95, add Windows support.

- [ ] Passing CI on Windows
- [ ] Documentation

Open Issues 
- [ ] https://github.com/opensearch-project/performance-analyzer/issues/121 **[Blocker]**
- [ ] https://github.com/opensearch-project/performance-analyzer/issues/300 **[Blocker]**
- [ ] https://github.com/opensearch-project/performance-analyzer/issues/301 **[Blocker]**
- [ ] https://github.com/opensearch-project/performance-analyzer/issues/302 **[Blocker]**
- [ ] https://github.com/opensearch-project/performance-analyzer/issues/303 **[Blocker]**

**Comment by setiah** [comment]
@kkhatua is someone working on this?

**Comment by HoffmannTom** [comment]
With the current Windows-pre-release i get the following stack:
Caused by: java.lang.IllegalStateException: separator cannot be multi-byte
        at org.opensearch.performanceanalyzer.reader_writer_shared.EventLog.<init>(EventLog.java:35) ~[?:?]
        at org.opensearch.performanceanalyzer.PerformanceAnalyzerPlugin.<init>(PerformanceAnalyzerPlugin.java:244) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:781) ~[opensearch-2.2.1-SNAPSHOT.jar:2.2.1-SNAPSHOT]
        at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:730) ~[opensearch-2.2.1-SNAPSHOT.jar:2.2.1-SNAPSHOT]
        at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:532) ~[opensearch-2.2.1-SNAPSHOT.jar:2.2.1-SNAPSHOT]
        at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195) ~[opensearch-2.2.1-SNAPSHOT.jar:2.2.1-SNAPSHOT]
        at org.opensearch.node.Node.<init>(Node.java:414) ~[opensearch-2.2.1-SNAPSHOT.jar:2.2.1-SNAPSHOT]
        at org.opensearch.node.Node.<init>(Node.java:341) ~[opensearch-2.2.1-SNAPSHOT.jar:2.2.1-SNAPSHOT]
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.2.1-SNAPSHOT.jar:2.2.1-SNAPSHOT]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.2.1-SNAPSHOT.jar:2.2.1-SNAPSHOT]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.2.1-SNAPSHOT.jar:2.2.1-SNAPSHOT]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.2.1-SNAPSHOT.jar:2.2.1-SNAPSHOT]
        ... 6 more

Tested on a current Win 11, 64 Bit

**Comment by peterzhuamazon** [comment]
Hi, just want to make sure this issue is closed, if all the tasks are completed.

Thanks.

**Comment by CEHENKLE** [comment]
@kkhatua What's the current status of this?  Are you targeting 2.6 for windows support?  If so, let's update the label.

**Comment by kkhatua** [comment]
Removed the label for `2.5.0` . We'll need to allocate resources for this, which is currently low on priority. I'll move it to `2.7.0`  because both, PA and the RCA project need to be visited for Windows support, and it is unlikely there will be a resource on this for Q1.
